# Generated by Django 3.1 on 2020-11-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_class_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='profile_pic',
            field=models.ImageField(upload_to='static images'),
        ),
    ]
