# Generated by Django 3.1 on 2020-11-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201118_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='profile_pic',
            field=models.ImageField(upload_to='home/static/images'),
        ),
    ]
