# Generated by Django 3.1 on 2020-11-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201120_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='last_paid',
            field=models.DateField(null=True),
        ),
    ]
