# Generated by Django 3.1 on 2020-11-23 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201123_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='last_paid',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
