# Generated by Django 3.1 on 2020-11-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201123_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='last_paid',
            field=models.DateField(),
        ),
    ]
