# Generated by Django 3.1 on 2020-11-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201123_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='profile_pic',
            field=models.ImageField(upload_to='profiles'),
        ),
    ]
